-- MySQL Script generated by MySQL Workbench
-- Пт 02 дек 2016 21:08:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yarik
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema yarik
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `yarik` DEFAULT CHARACTER SET utf8 ;
USE `yarik` ;

-- -----------------------------------------------------
-- Table `yarik`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yarik`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `info` MEDIUMTEXT NULL,
  `rate` INT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yarik`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yarik`.`messages` (
  `message_id` INT NOT NULL AUTO_INCREMENT,
  `text` MEDIUMTEXT NOT NULL,
  `rate` INT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`message_id`, `user_id`),
  INDEX `fk_messages_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_messages_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `yarik`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yarik`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yarik`.`tags` (
  `tag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yarik`.`users_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yarik`.`users_tags` (
  `user_id` INT NOT NULL,
  `tag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`, `tag`),
  INDEX `fk_users_has_tags_tags1_idx` (`tag` ASC),
  INDEX `fk_users_has_tags_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_has_tags_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yarik`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_tags_tags1`
    FOREIGN KEY (`tag`)
    REFERENCES `yarik`.`tags` (`tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yarik`.`messages_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yarik`.`messages_tags` (
  `message_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `tag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`message_id`, `user_id`, `tag`),
  INDEX `fk_messages_has_tags_tags1_idx` (`tag` ASC),
  INDEX `fk_messages_has_tags_messages1_idx` (`message_id` ASC, `user_id` ASC),
  CONSTRAINT `fk_messages_has_tags_messages1`
    FOREIGN KEY (`message_id` , `user_id`)
    REFERENCES `yarik`.`messages` (`message_id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_has_tags_tags1`
    FOREIGN KEY (`tag`)
    REFERENCES `yarik`.`tags` (`tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
